services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    image: "rabbitmq:3-management"
    networks:
      - messageApp

networks:
  messageApp:
    driver: bridge
